In [1]:
import os, cv2, copy
import numpy as np
from src.util import parseMKV, exportCalib, tcp2base, target2cam_color, composeH
from visualizer import CameraPoseVisualizer
from scipy.spatial.transform import Rotation

os.chdir(globals()['_dh'][0])

In [2]:
root = globals()['_dh'][0]
dir = "test"

out_dir = "calib"

debug = True

exportFrames = False
exportCalibration = False
exportRobotPose = True
exportPoseEstimation = False

In [3]:
from src.abb_parser import T_ROBParser

parser = T_ROBParser(folder_name=dir, root=root)#, cam2tcp="calib/cam2tcp_tsai_ir.npy")
# t_tcp2base, rVec_tcp2base, rMat_tcp2base, q_tcp2base = tcp2base(dir = dir)

parser.test()

tcp_T_cam:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
----------------


'd:\\GitHub\\AugRobFab-HandEyeCalibration\\test\\irnfov.mod'

In [4]:
# # if exportCalibration:
# #     mtx, dist = exportCalib(dir = dir, debug = debug)
# # else:
# #     data = np.load("%s/calibration.npz" % dir)
    
# #     mtx = data["mtx"]
# #     dist = data["dist"]

# # if exportFrames:
# #     parseMKV(dir = dir, exportDepth = False, debug = debug)

# if exportRobotPose:
    
# else:
#     data = np.load("%s/tcp2base.npz" % dir)

#     t_tcp2base = data["t"]
#     rVec_tcp2base = data["rVec"]
#     rMat_tcp2base = data["rMat"]
#     q_tcp2base = data["q"]
# if exportPoseEstimation:
#     rVec_target2cam, rMat_target2cam, t_target2cam, failedIdx = target2cam_color(dir = dir, mtx = mtx, dist = dist,
#                                                                 rx=copy.deepcopy(rVec_tcp2base),
#                                                                 tx=copy.deepcopy(t_tcp2base), 
#                                                                 boardDim = 30.45, boardSize = (24,17), debug = debug)
# else:
#     data = np.load("%s/target2cam.npz" % dir)
    
#     t_target2cam = data["t"]
#     rVec_target2cam = data["rVec"]
#     rMat_target2cam = data["rMat"]

#     failedIdx = data["failedIdx"]

In [5]:
# handEyeMethod = 4

# methods = [cv2.CALIB_HAND_EYE_TSAI, cv2.CALIB_HAND_EYE_PARK, cv2.CALIB_HAND_EYE_HORAUD, cv2.CALIB_HAND_EYE_ANDREFF, cv2.CALIB_HAND_EYE_DANIILIDIS]
# methods_s = ["tsai", "park", "horaud", "andreff", "daniilidis"]

# R_tcp2base = rVec_tcp2base
# R_target2cam = rVec_target2cam

# R_tcp2base = np.delete(R_tcp2base, failedIdx, 0)
# t_tcp2base = np.delete(t_tcp2base, failedIdx, 0)

# R_results = []
# t_results = []

# for i in range(len(methods)):
#     R_cam2tcp, t_cam2tcp = cv2.calibrateHandEye(R_tcp2base, t_tcp2base, R_target2cam, t_target2cam, method=methods[i])
#     R_results.append(R_cam2tcp)
#     t_results.append(t_cam2tcp)
#     # output results
#     print("--------------------------------------")
#     print("Method %s" % methods_s[i])
#     print("Rotation:\n", R_cam2tcp)
#     print("Translation:\n", t_cam2tcp.ravel())
#     print("Saving Method: %s..." % methods_s[i], end="")
#     np.save("%s/cam2tcp_%s_color" % (out_dir, methods_s[i]), composeH(R_results[i], t_results[i]))
#     print("Done!")
# print("--------------------------------------")
# print("Saving All Methods...", end="")
# np.savez("%s/_cam2tcp_color" % out_dir, tsai=composeH(R_results[0], t_results[0]),
#                                        park=composeH(R_results[1], t_results[1]),
#                                        horaud=composeH(R_results[2], t_results[2]),
#                                        andreff=composeH(R_results[3], t_results[3]),
#                                        daniilidis=composeH(R_results[4], t_results[4]))
# print("Done!")

In [6]:
# %matplotlib widget

# visualizer = CameraPoseVisualizer([0, 1500], [-500, 500], [0, 1500])

# cam2base = []

# M_cam2tcp = composeH(R_results[handEyeMethod], t_results[handEyeMethod])
# for i in range(len(t_tcp2base)):
#     M_tcp2base = composeH(rMat_tcp2base[i], t_tcp2base[i])
#     M_cam2base = np.matmul(M_tcp2base,M_cam2tcp)

#     cam2base.append(M_cam2base)

#     visualizer.extrinsic2pyramid(M_tcp2base, 'r', 100)
#     visualizer.extrinsic2pyramid(M_cam2base, 'b', 100)
# visualizer.show()

# np.savez("%s/%s" % (dir, "cam2base"), cam2base)